
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace App.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SysRole
{

    public SysRole()
    {

        this.SysUser = new HashSet<SysUser>();

        this.SysRight = new HashSet<SysRight>();

    }


    public string Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public System.DateTime CreateTime { get; set; }

    public string CreatePerson { get; set; }



    public virtual ICollection<SysUser> SysUser { get; set; }

    public virtual ICollection<SysRight> SysRight { get; set; }

}

}
